"""updated project table

Revision ID: d60b859748fb
Revises: a134659883a6
Create Date: 2021-06-05 14:35:39.175752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60b859748fb'
down_revision = 'a134659883a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'name')
    # ### end Alembic commands ###
